spring:
  datasource:
    url: jdbc:postgresql://localhost:49155/postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: authentication-service
  security:
    user:
      name: subhash
      password: subhash
server:
  port: 8484
eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/
security:
  oauth2:
    resource:
      token-info-uri: http://authentication-service/oauth/check_token
    client:
      client-id: javadeveloperzone
      client-secret: secret